### ISSUE TITLE
Getting video title

### ISSUE THREAD

**Issue by BanDroid** [matthew-asuncion/Fast-YouTube-to-MP3-Converter-API#15]
Hi, i would like to know how to get the video title before displaying the download button.

Is there a way to do that?

**Comment by matthew-asuncion** [comment]
Sorry but you can use out new widget with video thumbnail & title sample here [https://www.yt-download.org/api/widget/mp3/iiMrs3vOm_w](https://www.yt-download.org/api/widget/mp3/iiMrs3vOm_w)
