### ISSUE TITLE
Can i get an mp3 audio from youtube without a website?

### ISSUE THREAD

**Issue by alejandro0619** [matthew-asuncion/Fast-YouTube-to-MP3-Converter-API#6]
I'm coding a youtube audio bot for telegram, to download music from youtube (you can also download any type of video's audio). I'm looking for a API that doesn't matter if you are on a website or not. Can i use this API?

-Thank you

**Comment by matthew-asuncion** [comment]
You can just use our API in an iframe. You can't extract audio links using this API.
