### ISSUE TITLE
Loading is very slow

### ISSUE THREAD

**Issue by BanDroid** [matthew-asuncion/Fast-YouTube-to-MP3-Converter-API#7]
I have good internet, and try to use this on my application, and load my webview with this, the button shown up, but when i clicked on the download button, it takes an hour to respond and start downloading.

Is there any problem with the api?

**Comment by matthew-asuncion** [comment]
Sorry, currently API is not available for mobile apps. It will not work.

**Comment by BanDroid** [comment]
> Sorry, currently API is not available for mobile apps. It will not work.

How about in webview? I use webview in my apps to load your iframe, it works but the loading to download is very slow

**Comment by matthew-asuncion** [comment]
> > Sorry, currently API is not available for mobile apps. It will not work.
> 
> How about in webview? I use webview in my apps to load your iframe, it works but the loading to download is very slow

Sorry, it will not work.

**Comment by mohammadjouhari** [comment]
Can you please provide a way to return the stream data inseatd of html ?

**Comment by matthew-asuncion** [comment]
Sorry, just you can use API within iframe.
